using System.Text;

using DotNotes.Contracts;

namespace DotNotes.Notes.Files;

/// <summary>
/// The <c>index.md</c> beside a folder of notes, regenerated rather than maintained.
/// <para>
/// The memory this replaces keeps a hand-written <c>MEMORY.md</c>, and it drifts: a line describing
/// a note that has been deleted, a note nobody added a line for, a 41 KB document compressed into a
/// clause somebody wrote once. Nothing reconciles it, because nothing can -- a person writing prose
/// is not a process. Generating it from the notes beside it means the two cannot disagree.
/// </para>
/// </summary>
public static class NoteIndexFile
{
	/// <summary>The file's name, in every folder of notes.</summary>
	public const string FileName = "index.md";

	/// <summary>
	/// The marker that says a file is generated, in a form Obsidian hides in reading view. It is
	/// also what stops the index being crawled as a note: a listing of every note would otherwise
	/// match every search.
	/// </summary>
	public const string Marker = "%% Generated by DotNotes. Edits here are overwritten. %%";

	/// <summary>Whether a file is one of these, whatever it is called.</summary>
	public static bool IsGenerated(string content) =>
		content.Contains(Marker, StringComparison.Ordinal);

	/// <summary>
	/// The index for a folder.
	/// <para>
	/// Stable for stable input: the same notes always produce the same bytes, ordered by name. An
	/// index whose order wandered would be rewritten whenever an unrelated note changed, and on a
	/// synced store every rewrite is a replication and a stored revision.
	/// </para>
	/// </summary>
	/// <param name="title">What this folder is, as a heading.</param>
	/// <param name="headings">The notes beside the index.</param>
	/// <param name="lineEnding">What the existing file uses, so regenerating is not a diff on every line.</param>
	/// <param name="alsoIn">
	/// Notes in the other store for the same repository, listed rather than copied. It is the one
	/// bridge between the two stores a person browsing a vault gets, because a cross-store link is
	/// unresolvable in Obsidian and a mirror would be a second copy to keep true.
	/// </param>
	public static string Render(
		string title,
		IReadOnlyList<NoteHeading> headings,
		string lineEnding = "\n",
		IReadOnlyList<NoteHeading>? alsoIn = null)
	{
		var builder = new StringBuilder();

		builder.Append("---").Append(lineEnding);
		builder.Append("dotnotes-generated: true").Append(lineEnding);
		builder.Append("---").Append(lineEnding);
		builder.Append(Marker).Append(lineEnding).Append(lineEnding);
		builder.Append("# ").Append(title).Append(lineEnding).Append(lineEnding);

		if (headings.Count == 0)
		{
			builder.Append("No notes yet.").Append(lineEnding);
		}

		foreach (var heading in Ordered(headings))
		{
			builder.Append(Line(heading)).Append(lineEnding);
		}

		if (alsoIn is { Count: > 0 })
		{
			builder.Append(lineEnding).Append("## In the repository").Append(lineEnding).Append(lineEnding);

			foreach (var heading in Ordered(alsoIn))
			{
				builder.Append(Line(heading)).Append(lineEnding);
			}
		}

		return builder.ToString();
	}

	/// <summary>
	/// One note as a line: a link Obsidian resolves, then the gist where the indexing mode has
	/// written one and the author's description otherwise. The gist is preferred because it is
	/// written to be read in a list, which is exactly what this is.
	/// </summary>
	private static string Line(NoteHeading heading)
	{
		var summary = heading.Gist is { Length: > 0 } gist ? gist : heading.Description;
		var machines = heading.Machines.Count > 0 ? $" _({string.Join(", ", heading.Machines)})_" : string.Empty;
		var retired = heading.Superseded is not null ? " _(superseded)_" : string.Empty;

		return summary.Length > 0
			? $"- [[{heading.Name}]]{machines}{retired} — {summary}"
			: $"- [[{heading.Name}]]{machines}{retired}";
	}

	/// <summary>By name, because it is the only order that does not change when a note is edited.</summary>
	private static IEnumerable<NoteHeading> Ordered(IReadOnlyList<NoteHeading> headings) =>
		headings.OrderBy(heading => heading.Name, StringComparer.Ordinal);
}
